### ISSUE TITLE
Forward-port Liferay support to Vaadin 23.1+

### ISSUE THREAD

**Issue by mshabarov** [vaadin/portlet#221]
Vaadin Portlet support is currently implemented for Vaadin 14, but we need it in Vaadin 23 as well.

### Acceptance Criteria
- [x] Update Flow and CDI versions in Vaadin Portlet and apply needed changes to reflect differences between V14 and V23
- [x] Create CI build in Flow validation board for Vaadin 23
- [x] Forward-port the existing docs
- [x] Update starter projects with an additional branches for V23
- [x] Prepare release job and release alpha -> beta -> ga.

**Comment by mshabarov** [comment]
Deploy to Liferay fails locally with:
```
2022-04-22 10:40:22.647 ERROR [fileinstall-directory-watcher][DirectoryWatcher:1213] Unable to start bundle: webbundle:/Users/mikhail/workspace/vaadin/portlet-new/vaadin-portlet-liferay-integration-tests/liferay-tests-generic/target/liferay-ce-portal-7.4.3.5-ga5/osgi/war/liferay-tests-generic.war?Bundle-SymbolicName=liferay-tests-generic&Web-ContextPath=/liferay-tests-generic&protocol=file
com.liferay.portal.kernel.log.LogSanitizerException: org.osgi.framework.BundleException: Could not resolve module: liferay-tests-generic [1453]_  Unresolved requirement: Import-Package: com.github.luben.zstd; resolution:="optional"_  Unresolved requirement: Import-Package: com.sun.enterprise.web.connector.grizzly.comet; resolution:="optional"_  Unresolved requirement: Import-Package: com.sun.grizzly.comet; resolution:="optional"_  Unresolved requirement: Import-Package: com.sun.grizzly.tcp; resolution:="optional"_  Unresolved requirement: Import-Package: com.sun.grizzly.util.buf; resolution:="optional"_  Unresolved requirement: Import-Package: com.sun.grizzly.websockets; resolution:="optional"_  Unresolved requirement: Import-Package: io.quarkus.runtime; resolution:="optional"_  Unresolved requirement: Import-Package: javax.jnlp; resolution:="optional"_  Unresolved requirement: Import-Package: jdk.internal.misc; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.avalon.framework.logger; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.axis.tools.ant.wsdl; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.catalina; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.catalina.comet; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.catalina.connector; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.catalina.websocket; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.commons.pool2; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.commons.pool2.impl; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.coyote.http11.upgrade; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.log; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.poi.hssf.usermodel; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.poi.ss.usermodel; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.shiro; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.shiro.mgt; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.shiro.subject; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.shiro.web.env; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.shiro.web.subject; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.shiro.web.util; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.tomcat.util.codec.binary; resolution:="optional"_  Unresolved requirement: Import-Package: org.atmosphere.jboss.as.websockets; resolution:="optional"_  Unresolved requirement: Import-Package: org.atmosphere.jboss.as.websockets.servlet; resolution:="optional"_  Unresolved requirement: Import-Package: org.atmosphere.jboss.websockets; resolution:="optional"_  Unresolved requirement: Import-Package: org.atmosphere.jboss.websockets.frame; resolution:="optional"_  Unresolved requirement: Import-Package: org.atmosphere.jersey.util; resolution:="optional"_  Unresolved requirement: Import-Package: org.brotli.dec; resolution:="optional"_  Unresolved requirement: Import-Package: org.eclipse.jetty.continuation; resolution:="optional"_  Unresolved requirement: Import-Package: org.eclipse.jetty.websocket; resolution:="optional"_  Unresolved requirement: Import-Package: org.eclipse.jetty.websocket.api; resolution:="optional"_  Unresolved requirement: Import-Package: org.eclipse.jetty.websocket.server; resolution:="optional"_  Unresolved requirement: Import-Package: org.eclipse.jetty.websocket.servlet; resolution:="optional"_  Unresolved requirement: Import-Package: org.glassfish.grizzly; resolution:="optional"_  Unresolved requirement: Import-Package: org.glassfish.grizzly.comet; resolution:="optional"_  Unresolved requirement: Import-Package: org.glassfish.grizzly.http.server; resolution:="optional"_  Unresolved requirement: Import-Package: org.glassfish.grizzly.websockets; resolution:="optional"_  Unresolved requirement: Import-Package: org.jboss.servlet.http; resolution:="optional"_  Unresolved requirement: Import-Package: org.jboss.vfs; resolution:="optional"_  Unresolved requirement: Import-Package: org.junit.rules; resolution:="optional"_  Unresolved requirement: Import-Package: org.mortbay.util.ajax; resolution:="optional"_  Unresolved requirement: Import-Package: org.testng; resolution:="optional"_  Unresolved requirement: Import-Package: org.tukaani.xz; resolution:="optional"_  Unresolved requirement: Import-Package: sun.nio.ch; resolution:="optional"_  Unresolved requirement: Import-Package: weblogic.websocket; resolution:="optional"_  Unresolved requirement: Import-Package: weblogic.websocket.annotation; resolution:="optional"_  Unresolved requirement: Import-Package: com.liferay.portal.service; resolution:="optional"_  Unresolved requirement: Import-Package: com.liferay.portal.osgi.web.servlet.jsp.compiler; resolution:="optional"_  Unresolved requirement: Import-Package: com.liferay.portal.spring.context; resolution:="optional"_  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"_ [Sanitized]
	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428) ~[org.eclipse.osgi.jar:?]
	at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundle(DirectoryWatcher.java:1196) [bundleFile:?]
	at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundles(DirectoryWatcher.java:1229) [bundleFile:?]
	at com.liferay.portal.file.install.internal.DirectoryWatcher._process(DirectoryWatcher.java:1091) [bundleFile:?]
	at com.liferay.portal.file.install.internal.DirectoryWatcher.run(DirectoryWatcher.java:272) [bundleFile:?]
```

However, all the portlets deployed with no errors on the agents, but they redered as blank due to other error (?)

**Comment by mcollovati** [comment]
I do not have this error running locally. It's weird, seems like server is not running on Java 11.

But I have the same rendering problem that you see on agents. It seems that static bundle resources are not resolved. 
If i recall correctly the location of static assets changed in recent Vaadin version; now they are under `VAADIN/webapp/VAADIN/bundle`.

Changing configuration of maven war plugin for for the `vaadin-portlet-static` war in the following way seems so solve the problem (to be checked that all needed resources are included)

```xml
<execution>
    <configuration>
        <warName>vaadin-portlet-static</warName>
        <packagingIncludes>
            WEB-INF/lib/flow-client*.jar,WEB-INF/lib/vaadin-portlet*.jar,VAADIN/build/
        </packagingIncludes>

        <webResources>
            <resource>
                <!-- this is relative to the pom.xml directory -->
                <directory>target/classes/META-INF/VAADIN/webapp/
                </directory>
                <includes>
                    <include>**</include>
                </includes>
            </resource>
        </webResources>
    </configuration>
</execution>
```

**Comment by mshabarov** [comment]
@mcollovati many thanks for the tip, indeed, this was an issue.
